### PR TITLE
Add GRCh38 reference genome placeholder files

### PR DESCRIPTION
**Pull request by carmelinacharalambous**
4 files

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/59)

### CODE REVIEW

**Review by woook — COMMENTED** [review]
Please can you add a readme in the genomes directory as it will be easy to get confused as to what these reference files are used for.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/59#-:-MTjng597Bst-5Z9GoQc:b-we38ij)* status: 0 of 4 files reviewed, all discussions resolved

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/59)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous)

___
*[genomes/b37/hs37d5-fasta.tar.cpgz, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/59#-MTkIyMI3qA6BHThyj5P:-MTkIyMI3qA6BHThyj5Q:b2s2ria) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/f29b29e24e3a2bb84638b5767a1bc9f1568599d1/genomes/b37/hs37d5-fasta.tar.cpgz#L0)):*
What is this?

**Comment by carmelinacharalambous** [comment]
genomes/b37/hs37d5-fasta.tar.cpgz removed

**Review by woook — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/59#-:-MTkPx6w2gAVBnA2zDbu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous)

**Pull request merged**
