### PR TITLE
Copy of myeloid_multiqc_config_v1.0.2 with dx_sp added

### PR DESCRIPTION
**Pull request by Aisha-D**
Copy of myeloid_multiqc_config_v1.0.2.yaml with dx_sp added for eggd_multiqc v2.0.0 compatibility

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 115 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvM8f1h-0sMZttWRV:-MuGvM8f1h-0sMZttWRW:b-xku3mq) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L115)):*
> ```YAML
>     - fastqc:
>         module_tag:
>             - DNA
> ```

just double checking you've intentionally removed these?
```
- bcl2fastq:
        module_tag:
            - DNA
    - sentieon:
        module_tag:
            - DNA
```
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvZhy4r2DDixkcsFU:-MuGvZhy4r2DDixkcsFV:b-8nr3zd) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L134)):*
> ```YAML
>         MEDIAN_TARGET_COVERAGE: False
>         FOLD_ENRICHMENT: False
>     FastQC: False
> ```

these removed?
```
    bcl2fastq: False
    Sentieon: False
    Peddy: False
```
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvr9KEoO1rr4YCC7u:-MuGvr9KEoO1rr4YCC7v:b-antu2b) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L142)):*
> ```YAML
>         FREEMIX: 940               # contamination
>         250x: 950                  # coverage at 250x
>         summed_median: 960
> ```

these changed from:
```
        summed_median: 980
        PCT_AMPLIFIED_BASES: 990
```



_Code quote:_
```YAML
        summed_median: 960

        PCT_AMPLIFIED_BASES: 970
```
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 241 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwN4Y13duJ8T76KUG:-MuGwN4Y13duJ8T76KUH:b57k8q4) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L241)):*
> ```YAML
>         fn: '*.stats-fastqc.txt'
>     picard/alignment_metrics:
>         fn: '*.alignment_summary_metrics'
> ```

the fns were previously capitalised, is this intentionally changed / does it matter?
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 273 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwjG8Ckbk2OE9g9Zh:-MuGwjG8Ckbk2OE9g9Zi:by94p2z) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L273)):*
> ```YAML
> # Remove plots from HTML report
> remove_sections:
>     - picard_alignment_readlength # Mean readlength plot
> ```

this is being removed and the peddy plots now kept?
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 294 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwan68C9BNoDOi7Vx:-MuGwan68C9BNoDOi7Vy:b-rtmeak) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L294)):*
> ```YAML
>             - '*.pertarget_coverage.tsv'
>             # - '*.quality_by_cycle_metrics'
>             # - '*.quality_distribution_metrics'
> ```

can commented lines be removed?



_Code quote:_
```YAML
            # - '*.quality_by_cycle_metrics'

            # - '*.quality_distribution_metrics'

        verifybamid/QC:

            - '*.selfSM'

            # - '*.depthS
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 115 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvM8f1h-0sMZttWRV:-MuH0PzBEzK9dUG8TEeV:b-f6d04g) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L115)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

just double checking you've intentionally removed these?
```
- bcl2fastq:
        module_tag:
            - DNA
    - sentieon:
        module_tag:
            - DNA
```
</blockquote></details>

bcl2fastq, sentieon and peddy were previously hidden. This is now moved down to mention it once
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvZhy4r2DDixkcsFU:-MuH0t8C7YAD1iU6-tXv:bgqce63) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L134)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

these removed?
```
    bcl2fastq: False
    Sentieon: False
    Peddy: False
```
</blockquote></details>

As mentioned above - bcl2fastq, sentieon and peddy were previously hidden. This is now moved down to mention it once
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 273 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwjG8Ckbk2OE9g9Zh:-MuH0eEODrM2HUDqxi0w:bfbcubs) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L273)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is being removed and the peddy plots now kept?
</blockquote></details>

peddy files are not generated so multiqc won't present it. I think this was to force it not to present in case peddy files were present
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 294 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwan68C9BNoDOi7Vx:-MuH0orkEnRd3UPrgn_I:b-d7bhn0) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L294)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can commented lines be removed?
</blockquote></details>

will do

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Aisha-D, @jethror1, and @sophie22)

___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvr9KEoO1rr4YCC7u:-MuH4a2R3KZNuTjVQS0h:bty84ya) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L142)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

these changed from:
```
        summed_median: 980
        PCT_AMPLIFIED_BASES: 990
```
</blockquote></details>

only so that columns come one after the other in the right order in the table
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 241 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwN4Y13duJ8T76KUG:-MuH4n8I0TKNV8Aubvcp:b-hkzifm) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L241)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

the fns were previously capitalised, is this intentionally changed / does it matter?
</blockquote></details>

not matters too much, previous ones were incorrect (sentieon for WES/Dias has it capitalised, Picard in myeloid does not). Previous values were incorrect, but worked regardless
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 273 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwjG8Ckbk2OE9g9Zh:-MuH56-pBr73RnfSOqTB:b9ku3qz) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L273)):*
> Previous values were incorrect, but worked regardless
peddy lines in the config file are from the file I originally copied from moka-guys that I used as a template, but it is not relevant to our QC reports

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Aisha-D, @jethror1, and @sophie22)

___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 115 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvM8f1h-0sMZttWRV:-MuH8XdfBbOxldAh94n9:bs8vjlq) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L115)):*
> hidden
these modules are not part of the QC for myeloid (data is not provided) not relevant
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 294 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwan68C9BNoDOi7Vx:-MuH5W-F4Y9FOLep7TJz:blj6hvk) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L294)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

will do
</blockquote></details>

reason why I left them in is so that in the future if any of these other metrics need to be included, we can easily have them (the files are being generated by the pipeline)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @sophie22)

___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGvr9KEoO1rr4YCC7u:-MuH_cyNCcIOjrhryPh_:b-cmtuou) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L142)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

so the changed values are correct ?
</blockquote></details>

yep the values are right
___
*[dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml, line 294 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119#-MuGwan68C9BNoDOi7Vx:-MuHaBwuALrbQINm458j:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/bb1e9bdd75335079e1a6bd24979da93c51e988b5/dynamic_files/multiqc_config/MYE_multiqc_config_v2.0.0.yaml#L294)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

reason why I left them in is so that in the future if any of these other metrics need to be included, we can easily have them (the files are being generated by the pipeline)
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/119)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @sophie22)

**Pull request merged**
