### PR TITLE
Added placeholders for gnomad exome vcf/index

### PR DESCRIPTION
**Pull request by mattgarner**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mattgarner and @woook)

___
*[annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz, line 14 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121#-Mup_4edAtrgrgfm3IbU:-Mup_4ee-7-VCPZChUFU:b-stic2z) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/43d7bc5b5730f3757172d926d71a98fc484741fe/annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz#L14)):*
> ```
> wget http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta.fai
> 
> wget https://github.com/samtools/bcftools/releases/download/1.13/bcftools-1.13.tar.bz2
> ```

Any reason for not grabbing the latest release?



_Code quote:_
```
https://github.com/samtools/bcftools/releases
```
___
*[annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz, line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121#-Mup_L8z9guZX70f8-cC:-Mup_L8z9guZX70f8-cD:bad60e9) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/43d7bc5b5730f3757172d926d71a98fc484741fe/annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz#L32)):*
> ```
> 
> # Upload
> unset DX_WORKSPACE_ID
> ```

Is this necessary?



_Code quote:_
```
unset DX_WORKSPACE_ID
```

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mattgarner and @woook)

___
*[annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz, line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121#-Mup_L8z9guZX70f8-cC:-MuqH-pdDOc70neONGHs:b-7la96m) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/43d7bc5b5730f3757172d926d71a98fc484741fe/annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz#L32)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

```
Due to differences in the execution environment, in order to upload or download files from your parent projects, you must first run the following two commands in your workstation:
```

See https://documentation.dnanexus.com/developer/cloud-workstations/cloud-workstation#step-3-set-up-the-workspace

**Review by mattgarner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @woook)

___
*[annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz, line 14 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121#-Mup_4edAtrgrgfm3IbU:-MuqfEox9pR05wRZou33:b-886gsx) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/43d7bc5b5730f3757172d926d71a98fc484741fe/annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz#L14)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Any reason for not grabbing the latest release?
</blockquote></details>

Fixed

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @woook)

___
*[annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz, line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121#-Mup_L8z9guZX70f8-cC:-MutgSyeBAx3gUt7bE8T:b52e7c2) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/43d7bc5b5730f3757172d926d71a98fc484741fe/annotation/b37/gnomad/gnomad.exomes.r2.0.2.sites.noVEP_normalised_decomposed_PASS.vcf.gz#L32)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

```
Due to differences in the execution environment, in order to upload or download files from your parent projects, you must first run the following two commands in your workstation:
```

See https://documentation.dnanexus.com/developer/cloud-workstations/cloud-workstation#step-3-set-up-the-workspace
</blockquote></details>

Ah - I didn't realise that you were in a cloud workstation.

**Review by woook — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
