### PR TITLE
230421 version of genepanels

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/220)

### CODE REVIEW

**Comment by oniblock** [comment]
*[`dynamic_files/gene_panels/230421_genepanels.tsv` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/220#-NTwl7Zf6SUmbCABAcOS:-NTwl7Zf6SUmbCABAcOT:bhspk1p) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/4d9801677a045ca5e9f3ea10313fd229caaf2e4b/dynamic_files/gene_panels/230421_genepanels.tsv#L19)):*
> ```TSV
> R100.3_Rare syndromic craniosynostosis or isolated multisuture synostosis_P	Rare syndromic craniosynostosis or isolated multisuture synostosis_4.0	HGNC:11772
> R100.3_Rare syndromic craniosynostosis or isolated multisuture synostosis_P	Rare syndromic craniosynostosis or isolated multisuture synostosis_4.0	HGNC:11773
> R100.3_Rare syndromic craniosynostosis or isolated multisuture synostosis_P	Rare syndromic craniosynostosis or isolated multisuture synostosis_4.0	HGNC:11842
> ```

hi @Yu-jinKim - can't see the change between these, but looks ok - can you just confirm for me?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/220)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @oniblock)

___
*[`dynamic_files/gene_panels/230421_genepanels.tsv` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/220#-NTwl7Zf6SUmbCABAcOS:-NTwoNGT6ObX8CPX46HL:b-6ashia) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/4d9801677a045ca5e9f3ea10313fd229caaf2e4b/dynamic_files/gene_panels/230421_genepanels.tsv#L19)):*
<details><summary><i>Previously, oniblock wrote…</i></summary><blockquote>

hi @Yu-jinKim - can't see the change between these, but looks ok - can you just confirm for me? 
</blockquote></details>

it looks like R100.3 didn't exist in the previous genepanels:
```
dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-GJJ7Vx8433Gz96yp8V98X74f | grep R100.3
echo $?
1
```

**Comment by oniblock** [comment]
*[`dynamic_files/gene_panels/230421_genepanels.tsv` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/220#-NTwl7Zf6SUmbCABAcOS:-NTwzyv6D62r4qHhi-vM:b-90wpli) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/4d9801677a045ca5e9f3ea10313fd229caaf2e4b/dynamic_files/gene_panels/230421_genepanels.tsv#L19)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

it looks like R100.3 didn't exist in the previous genepanels:
```
dx cat project-Fkb6Gkj433GVVvj73J7x8KbV:file-GJJ7Vx8433Gz96yp8V98X74f | grep R100.3
echo $?
1
```
</blockquote></details>

cool, thank you for checking

**Review by oniblock — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/220#-:-NTx-3jJ4_pjJuVwZc7L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

**Pull request merged**
