### PR TITLE
Bed files for myeloid and SNP

### PR DESCRIPTION
**Pull request by carmelinacharalambous**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54)* status: all files reviewed, 13 unresolved discussions (waiting on @carmelinacharalambous and @woook)

___
*[bed_files/._README.md, line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXN7ul8IcaFWKM0nbU:-MSXN7ul8IcaFWKM0nbV:bnhhro4) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/._README.md#L1)):*
> ```
> Mac OS X        2��ATTR;�����*�*$com.apple.metadata:_kMDItemUserTagsbplist00�
> ```
What is this file? Can it be removed?
___
*[bed_files/README.md, line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXNmSO4YgYtgyIjvFP:-MSXNmSO4YgYtgyIjvFQ:bzc9bi6) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L40)):*
> ```
> v0.1
> ```
Should this be v1.0 if it's the first live version? Is this our versioning or Twist's?
___
*[bed_files/README.md, line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXO_5H6cU90PjNkOVk:-MSXO_5H6cU90PjNkOVl:b7tokpr) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L40)):*
> ```
> /bed_files/b38/kits/myeloid/coding_unrestricted_GRCh38_myeloid_v0.1.bed
> ```
This bed contains additional fields - what info do they contain?
___
*[bed_files/README.md, line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOzKsCy6h3nALrrf6:-MSXOzKtDYcf6A6xYRqW:bl7tj9u) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L41)):*
> ```
> This is the bed file provided by TWIST and includes all exons of the genes of interest.
> ```
Is there any flank? If not please state this as +/- 0bp.
___
*[bed_files/README.md, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOftA4AAnGdxuuVZX:-MSXOftA4AAnGdxuuVZY:b-pw8ymm) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L42)):*
> ```
>  /bed_files/b38/kits/myeloid/coding_restricted_GRCh38_myeloid_v0.1.bed
> ```
This bed contains additional fields - what info do they contain?
___
*[bed_files/README.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXNVEZ9XQuOW8f-RfR:-MSXNVEZ9XQuOW8f-RfS:b-a7bmdc) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L43)):*
> ```
> subset
> ```
How is the subset defined?
___
*[bed_files/README.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPJ4Z2AtReu0wNuug:-MSXPJ4Z2AtReu0wNuuh:b-e0ll8j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L43)):*
> ```
> This is the bed file provided by TWIST and includes a subset of exons of the genes of interest.
> ```
Is there any flank? If not please state this as +/- 0bp.
___
*[bed_files/README.md, line 49 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPfbB3UD-dKV54bDw:-MSXPfbC6GEdOzPj0SdB:b-2vwu19) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L49)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> * :sleeping_bed: /bed_files/b38/kits/snp_genotyping/snp_genotyping_GRCh38_v1.0.bed
> > This is the bed file provided by NimaGen and includes all SNP positions
> * :sleeping_bed: /bed_files/b38/kits/snp_genotyping/snp_genotyping_amplicon_GRCh38_v1.0.bed
> > This is the bed file provided by NimaGen that includes all amplicon coordinates. This file is used by eggd_picardqc_v1.0.0
> ```
</details>

What are the additional fields?
___
*[bed_files/b38/kits/myeloid/._coding_restricted_GRCh38_myeloid_v0.1.bed, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOH2RELsdH2T7b3Uf:-MSXOH2RELsdH2T7b3Ug:brc1ph1) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/myeloid/._coding_restricted_GRCh38_myeloid_v0.1.bed#L0)):*
What is this? Can it be removed?
___
*[bed_files/b38/kits/myeloid/._coding_unrestricted_GRCh38_myeloid_v0.1.bed, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOK341eEJ-9uvsY0d:-MSXOK341eEJ-9uvsY0e:brc1ph1) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/myeloid/._coding_unrestricted_GRCh38_myeloid_v0.1.bed#L0)):*
What is this? Can it be removed?
___
*[bed_files/b38/kits/myeloid/._probes_GRCh38_myeo_v1.0.bed, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOKWl9pP60YYwRUy4:-MSXOKWl9pP60YYwRUy5:brc1ph1) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/myeloid/._probes_GRCh38_myeo_v1.0.bed#L0)):*
What is this? Can it be removed?
___
*[bed_files/b38/kits/snp_genotyping/._snp_genotyping_amplicon_GRCh38_v1.0.bed, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPV1q2m2HjJIRM9zb:-MSXPV1q2m2HjJIRM9zc:brc1ph1) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/snp_genotyping/._snp_genotyping_amplicon_GRCh38_v1.0.bed#L0)):*
What is this? Can it be removed?
___
*[bed_files/b38/kits/snp_genotyping/._snp_genotyping_GRCh38_v1.0.bed, line 0 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPXP9E1kcifpzuVXP:-MSXPXP9E1kcifpzuVXQ:brc1ph1) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/snp_genotyping/._snp_genotyping_GRCh38_v1.0.bed#L0)):*
What is this? Can it be removed?

**Review by woook — APPROVED** [review]
Do you need anything from me? Looks like all of @mattgarner 's questions are for @carmelinacharalambous ?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-:-MSX_mXz5XJ9KfU3uIMo:be93uql)* status: all files reviewed, 13 unresolved discussions (waiting on @carmelinacharalambous)

**Comment by carmelinacharalambous** [comment]
Add myeloid and nimagen bed files to 001_reference repository.

There are 3 bed files for myeloid (GRCh38): 
1. coding_unrestricted_GRCh38_myeloid_v1.0.bed -> includes all exons of the genes of interest +/- 5bp.
2. coding_restricted_GRCh38_myeloid_v1.0.bed ->  includes only clinically significant exons  +/- 5bp.
3. probes_GRCh38_myeo_v1.0.bed -> includes all probes coordinates for the myeloid panel


There are 2 bed files for nimagen (GRCh38):
1. snp_genotyping_GRCh38_v1.0.bed -> includes all SNP positions
2. snp_genotyping_amplicon_GRCh38_v1.0.bed -> includes all amplicon coordinates

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54)* status: 6 of 12 files reviewed, 8 unresolved discussions (waiting on @carmelinacharalambous and @mattgarner)

___
*[bed_files/README.md, line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXNmSO4YgYtgyIjvFP:-MShnx_sEDpBZbqCi4j2:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L40)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> v0.1
> ```
Should this be v1.0 if it's the first live version? Is this our versioning or Twist's?
</blockquote></details>

Done
___
*[bed_files/README.md, line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXO_5H6cU90PjNkOVk:-MShnyi563DiCaQ3zI4t:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L40)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> /bed_files/b38/kits/myeloid/coding_unrestricted_GRCh38_myeloid_v0.1.bed
> ```
This bed contains additional fields - what info do they contain?
</blockquote></details>

Done
___
*[bed_files/README.md, line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOzKsCy6h3nALrrf6:-MSho-F72tLg_4p1GEJU:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> This is the bed file provided by TWIST and includes all exons of the genes of interest.
> ```
Is there any flank? If not please state this as +/- 0bp.
</blockquote></details>

Done
___
*[bed_files/README.md, line 42 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOftA4AAnGdxuuVZX:-MSho1IyAxuUxI6HoxV7:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>  /bed_files/b38/kits/myeloid/coding_restricted_GRCh38_myeloid_v0.1.bed
> ```
This bed contains additional fields - what info do they contain?
</blockquote></details>

Done
___
*[bed_files/README.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXNVEZ9XQuOW8f-RfR:-MSho2F9DF3jJc6ZiQzl:bel9dkf) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> subset
> ```
How is the subset defined?
</blockquote></details>

Is this our modification of the full Twist bed, or was it provided directly by Twist?
___
*[bed_files/README.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPJ4Z2AtReu0wNuug:-MShoChA0SjbMF0e_pZ2:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> This is the bed file provided by TWIST and includes a subset of exons of the genes of interest.
> ```
Is there any flank? If not please state this as +/- 0bp.
</blockquote></details>

Done

**Review by mattgarner — COMMENTED** [review]
> Reviewed 2 of 6 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @carmelinacharalambous and @mattgarner)

___
*[bed_files/b38/kits/myeloid/._probes_GRCh38_myeo_v1.0.bed, line  at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOKWl9pP60YYwRUy4:-MSi3D-Y3-B2wl5HAQG8:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/myeloid/._probes_GRCh38_myeo_v1.0.bed#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What is this? Can it be removed?
</blockquote></details>

Done
___
*[bed_files/b38/kits/myeloid/._coding_restricted_GRCh38_myeloid_v0.1.bed, line  at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOH2RELsdH2T7b3Uf:-MSi3BSS1jcpgXyY53bv:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/myeloid/._coding_restricted_GRCh38_myeloid_v0.1.bed#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What is this? Can it be removed?
</blockquote></details>

Done
___
*[bed_files/b38/kits/myeloid/._coding_unrestricted_GRCh38_myeloid_v0.1.bed, line  at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXOK341eEJ-9uvsY0d:-MSi3Khw8RRwURLgyWlB:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/myeloid/._coding_unrestricted_GRCh38_myeloid_v0.1.bed#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What is this? Can it be removed?
</blockquote></details>

Done

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54)* status: all files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous)

___
*[bed_files/._README.md, line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXN7ul8IcaFWKM0nbU:-MSlG3dL2F4uLg3nUJDp:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/._README.md#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> Mac OS X        2��ATTR;�����*�*$com.apple.metadata:_kMDItemUserTagsbplist00�
> ```
What is this file? Can it be removed?
</blockquote></details>

Done
___
*[bed_files/README.md, line 49 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPfbB3UD-dKV54bDw:-MSlG9Lm0CyeamLAXd9f:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L49)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> * :sleeping_bed: /bed_files/b38/kits/snp_genotyping/snp_genotyping_GRCh38_v1.0.bed
> > This is the bed file provided by NimaGen and includes all SNP positions
> * :sleeping_bed: /bed_files/b38/kits/snp_genotyping/snp_genotyping_amplicon_GRCh38_v1.0.bed
> > This is the bed file provided by NimaGen that includes all amplicon coordinates. This file is used by eggd_picardqc_v1.0.0
> ```
What are the additional fields?
</blockquote></details>

Done
___
*[bed_files/b38/kits/snp_genotyping/._snp_genotyping_amplicon_GRCh38_v1.0.bed, line  at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPV1q2m2HjJIRM9zb:-MSlGP-q4_uvKJRJfnuP:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/snp_genotyping/._snp_genotyping_amplicon_GRCh38_v1.0.bed#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What is this? Can it be removed?
</blockquote></details>

Done
___
*[bed_files/b38/kits/snp_genotyping/._snp_genotyping_GRCh38_v1.0.bed, line  at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXPXP9E1kcifpzuVXP:-MSlGPz21yaB8sLhxSdm:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/b38/kits/snp_genotyping/._snp_genotyping_GRCh38_v1.0.bed#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What is this? Can it be removed?
</blockquote></details>

Done

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[bed_files/README.md, line 43 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/54#-MSXNVEZ9XQuOW8f-RfR:-MT-rFXJ8762_ajNQUm7:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/b64787631cca54959cf9156535d1014074e38f2f/bed_files/README.md#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this our modification of the full Twist bed, or was it provided directly by Twist?
</blockquote></details>

Done

**Pull request merged**
