### PR TITLE
WES panelapp bed

### PR DESCRIPTION
**Pull request by mattgarner**
```
# Download exons_nirvana, which contains regions of all refseqs NMs in the nirvana cache
dx download project-Fkb6Gkj433GVVvj73J7x8KbV:file-Fq18Yp0433GjB7172630p9Yv

# Download g2t - contains current transcript selection
dx download project-Fkb6Gkj433GVVvj73J7x8KbV:file-G1qQ9JQ433GZ4G8Q5Z1xy0ZF

# Extract transcript IDs (NM_*) from g2t
grep -P "\tclinical_transcript\t" 210408_g2t.tsv | cut -f 2 | sort | uniq | grep ^NM > panelapp_GMS_transcripts_210408

# Extract exons for those transcripts from exons_nirvana to make bed file, drop unnecessary fields
while read tx; do grep -P "\t$tx\t" exons_nirvana2010_no_PAR_Y.tsv; done < panelapp_GMS_transcripts_210408 | cut -f 1,2,3,5 | sort -k1V -k2n -k3n > panelapp_GMS_transcripts_210408.bed

# Check that all transcripts were found, and are present in bed
cut -f 4 panelapp_GMS_transcripts_210408.bed | sort | uniq > bed_txs  # This contains a sorted list of txs in the bed

# Compare the input transcript list with list of transcripts in bed file
diff bed_txs panelapp_GMS_transcripts_210408  
2962a2963
> NM_173471.3

# Issue found
# NM_173471 present in transcripts list, but not present in panelapp_GMS_transcripts_210408.bed

# Explanation - error in Nirvana cache, CDS regions for this transcript are missing from the Cache data
zcat GRCh37_RefSeq_26.gff.gz | grep NM_173471.3 | grep CDS
# No result

# Search instead for exons
zcat GRCh37_RefSeq_26.gff.gz | grep NM_173471.3 | grep exon
chr3	RefSeq	exon	66119285	66119661	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_173471.3"; transcript_type "mRNA"; exon_number 1; internal_gene_id "5491"; 
# Only one exon present - incorrect

# Find other transcripts for this gene in the cache
zcat GRCh37_RefSeq_26.gff.gz | grep 'internal_gene_id "5491"' | grep CDS
chr3	RefSeq	CDS	66293701	66293736	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 2; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66312475	66312579	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 3; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66313756	66313803	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 4; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66396788	66396832	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 5; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66413284	66413353	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 6; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66419902	66419966	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 7; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66420953	66421026	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 8; internal_gene_id "5491"; 
chr3	RefSeq	CDS	66428114	66428231	.	+	.	gene_id "115286"; gene_name "SLC25A26"; transcript_id "NM_001164796.1"; transcript_type "protein_coding"; tag "canonical"; protein_id "NP_001158268.1"; exon_number 9; internal_gene_id "5491"; 

# CDS for transcript NM_001164796.1 is present in the Cache, and contains the expected number of regions.

# To include NM_173471.3 regions within this bed, we will add the regions from another source - UCSC table browser:
cat ucsc_NM_173471.3.bed   # Table browser output for NM_173471.3
chr3	66271520	66271553	NM_173471.3_cds_1_0_chr3_66271521_f	0	+
chr3	66286967	66287124	NM_173471.3_cds_2_0_chr3_66286968_f	0	+
chr3	66293626	66293736	NM_173471.3_cds_3_0_chr3_66293627_f	0	+
chr3	66312474	66312579	NM_173471.3_cds_4_0_chr3_66312475_f	0	+
chr3	66313755	66313803	NM_173471.3_cds_5_0_chr3_66313756_f	0	+
chr3	66396787	66396832	NM_173471.3_cds_6_0_chr3_66396788_f	0	+
chr3	66413283	66413353	NM_173471.3_cds_7_0_chr3_66413284_f	0	+
chr3	66419901	66419966	NM_173471.3_cds_8_0_chr3_66419902_f	0	+
chr3	66420952	66421026	NM_173471.3_cds_9_0_chr3_66420953_f	0	+
chr3	66428113	66428231	NM_173471.3_cds_10_0_chr3_66428114_f	0	+

# Remove chr
# Add 5bp flank to be consistent with the other regions in panelapp bed
# Keep only NM_* in column 4
# Drop columns 5-6
cat ucsc_NM_173471.3.bed | sed s/^chr// | awk -F "\t" '{OFS="\t"; print $1,$2-5,$3+5,$4}' | awk -F "_cds" '{print $1}' > NM_173471.3.bed
cat NM_173471.3.bed
3	66271515	66271558	NM_173471.3
3	66286962	66287129	NM_173471.3
3	66293621	66293741	NM_173471.3
3	66312469	66312584	NM_173471.3
3	66313750	66313808	NM_173471.3
3	66396782	66396837	NM_173471.3
3	66413278	66413358	NM_173471.3
3	66419896	66419971	NM_173471.3
3	66420947	66421031	NM_173471.3
3	66428108	66428236	NM_173471.3

# Add to panelapp bed
cat NM_173471.3.bed >> panelapp_GMS_transcripts_210408.bed

# Re-sort panelapp bed
sort -k1V -k2n -k3n -k4V -o panelapp_GMS_transcripts_210408 panelapp_GMS_transcripts_210408

# Make new list of transcripts in panelapp bed
cut -f 4 panelapp_GMS_transcripts_210408.bed | sort | uniq > bed_txs2

# Compare the input transcript list with list of transcripts in updated bed file
diff bed_txs2 panelapp_GMS_transcripts_210408
# No diff

# panelapp_GMS_transcripts_210408.bed now contains all transcripts currently being tested
```

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/81)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/81)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[bed_files/README.md, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/81#-M_u0qEx1pAXfXczQfrp:-M_u0qEy60d4D-Db250Y:b9flina) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/7804ed4de70ececa48c91440abb761bae7d117ef/bed_files/README.md#L55)):*
> ```
> panelapp_GMS_transcripts_210408.bed
> ```
Does this bed file include the child-onset spastic paraplegia panel?

**Comment by mattgarner** [comment]
It does:

```
# Downloaded panel tsv from panelapp then extracted HGNC column from file.
# Restricted to green genes
# This was performed manually since the file is tab delimited but contains tabs within fields
# causing misalignment of columns 

# Sanity check the panelapp file
head HSPC_HGNCs
HGNC:61
HGNC:225
HGNC:315
HGNC:10648
HGNC:9722
HGNC:443
HGNC:572
HGNC:573
HGNC:574
HGNC:575

wc -l HSPC_HGNCs
69

Check all HGNC IDs are present in our transcript list:
while read hgnc; do 
  if grep -qP "^${hgnc}\t" 210408_g2t.tsv; then 
    echo "SUCCESS"
  else
    echo "MISSING $hgnc"
  fi; done < HSPC_HGNCs | sort | uniq -c

69 SUCCESS

# Sanity check - add an ID which we know should fail
echo "HGNC:0" >> HSPC_HGNCs

# Run again
while read hgnc; do 
  if grep -qP "^${hgnc}\t" 210408_g2t.tsv; then 
    echo "SUCCESS"
  else
    echo "MISSING $hgnc"
  fi; done < HSPC_HGNCs | sort | uniq -c

  1 HGNC:0
69 SUCCESS

# Missing IDs are correctly detected

**Comment by woook** [comment]
___
*[bed_files/README.md, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/81#-M_u0qEx1pAXfXczQfrp:-M_ukhfZ10POnrYhFmGE:bujs5r9) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/7804ed4de70ececa48c91440abb761bae7d117ef/bed_files/README.md#L55)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

> ```
> panelapp_GMS_transcripts_210408.bed
> ```
Does this bed file include the child-onset spastic paraplegia panel? 
</blockquote></details>

Addressed in PR comments.

**Review by woook — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
