### PR TITLE
Vw 112 vep annotation

### PR DESCRIPTION
**Pull request by Addy81**
Add placeholders for:
- CADD Indels annotation
- SpliceAI annotation
- REVEL annotation
- VEP resources
- HGMD annotation
- Clinvar annotation

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137)* status: 11 of 29 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @jethror1)

___
*[`annotation/b37/vep/homo_sapiens_refseq_vep_105_GRCh37.tar.gz` line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137#-N2MlrFo7qeKJTBjPpb4:-N2MlrFpC403qEwMYXZ3:b-fwzbdc) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/f1b7a3ac8c332f6cef94635db27429b2cf42b623/annotation/b37/vep/homo_sapiens_refseq_vep_105_GRCh37.tar.gz#L3)):*
> ```
> Provenance described in: https://cuhbioinformatics.atlassian.net/wiki/spaces/VW/pages/2591981582/220304+-+VEP+105.0+Resources
> 
> DNAnexus link: project-Fkb6Gkj433GVVvj73J7x8KbV:file-G8yzbGQ4Yjj08GJX946x4BB7
> ```

file ID doesn't match name of placeholder file:

```
$ dx describe project-Fkb6Gkj433GVVvj73J7x8KbV:file-G8yzbGQ4Yjj08GJX946x4BB7
Result 1:
ID                    file-G8yzbGQ4Yjj08GJX946x4BB7
Class                 file
Project               project-Fkb6Gkj433GVVvj73J7x8KbV
Folder                /annotation/b38/vep
Name                  homo_sapiens_refseq_vep_105_GRCh38.tar.gz
State                 closed
Visibility            visible
Types                 -
Properties            -
Tags                  -
Outgoing links        -
Created               Fri Mar 25 17:24:02 2022
Created by            toutoua
 via the job          job-G8yzQVQ4jKXBvzG6151fJgbJ
Last modified         Fri Apr  1 10:49:20 2022
Media type            application/gzip
archivalState         "live"
Size                  13.78 GB
cloudAccount          "cloudaccount-dnanexus"
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 15 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @jethror1)

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`annotation/b37/vep/homo_sapiens_refseq_vep_105_GRCh37.tar.gz` line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137#-N2MlrFo7qeKJTBjPpb4:-N2Mncq88mGSA5ffnCLp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/f1b7a3ac8c332f6cef94635db27429b2cf42b623/annotation/b37/vep/homo_sapiens_refseq_vep_105_GRCh37.tar.gz#L3)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

file ID doesn't match name of placeholder file:

```
$ dx describe project-Fkb6Gkj433GVVvj73J7x8KbV:file-G8yzbGQ4Yjj08GJX946x4BB7
Result 1:
ID                    file-G8yzbGQ4Yjj08GJX946x4BB7
Class                 file
Project               project-Fkb6Gkj433GVVvj73J7x8KbV
Folder                /annotation/b38/vep
Name                  homo_sapiens_refseq_vep_105_GRCh38.tar.gz
State                 closed
Visibility            visible
Types                 -
Properties            -
Tags                  -
Outgoing links        -
Created               Fri Mar 25 17:24:02 2022
Created by            toutoua
 via the job          job-G8yzQVQ4jKXBvzG6151fJgbJ
Last modified         Fri Apr  1 10:49:20 2022
Media type            application/gzip
archivalState         "live"
Size                  13.78 GB
cloudAccount          "cloudaccount-dnanexus"
```
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/137)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
