### PR TITLE
Config file for automation TWE

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Contains:
- dias single
- dias multi
- MultiQC

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @oniblock and @Yu-jinKim)

___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsmHJDMWBkLg0As2X:-NOOsmHJDMWBkLg0As2Y:b-w7l33v) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L72)):*
> ```JSON
>                     "$dnanexus_link": "INPUT-SAMPLESHEET"
>                 },
>                 
> ```

blank line



_Code quote:_
```JSON
···············
```
___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsp7k75db27CzH3sE:-NOOsp7lCeGMq34dpWmW:b-w7l33v) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L84)):*
> ```JSON
>                     }
>                 },
> ```

blank line
___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 92 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsqCj86-Yf8rOa_LV:-NOOsqCj86-Yf8rOa_LW:b-8nrx3v) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L92)):*
> ```JSON
>                     }
>                 },
> ```

line is blank
___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsrTs3eXzs1UyDFL8:-NOOsrTs3eXzs1UyDFL9:b-9pxoer) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L95)):*
> ```JSON
>                 "stage-G5j1jvj433GYYY25B5jKxFYp.female_threshold": 60,
>                 "stage-G5j1jvj433GYYY25B5jKxFYp.male_threshold": 1
> ```

nothing on this line

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @oniblock)

___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsmHJDMWBkLg0As2X:-NOP8URj41gXdmocLram:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L72)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.
___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsp7k75db27CzH3sE:-NOP8U1IB_XG_ae5HBWd:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L84)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

blank line
</blockquote></details>

Done.
___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 92 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsqCj86-Yf8rOa_LV:-NOP8Tj34fU7pQhKVvgl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L92)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

line is blank
</blockquote></details>

Done.
___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 95 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOOsrTs3eXzs1UyDFL8:-NOP8TUJ2NFz7Z_A2OIP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L95)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

nothing on this line
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @oniblock and @Yu-jinKim)

___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOPAucP0gF6OeP3rxuM:-NOPAucP0gF6OeP3rxuN:bcvv1bt) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L2)):*
> ```JSON
> {
>     "name": "Config for Twist assay",
> ```

should this be `Twist whole exome`? Technically myeloid is also a Twist capture assay



_Code quote:_
```JSON
Twist
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @oniblock)

___
*[`dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210#-NOPAucP0gF6OeP3rxuM:-NOTw7bb5iDu1u8SYb_A:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_Reference/blob/ca14211fd52a437cead268afd535f530ee39ca14/dynamic_files/eggd_conductor_configs/assay_configs/TWE/eggd_conductor_dias_TWE_config_v1.0.0.json#L2)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be `Twist whole exome`? Technically myeloid is also a Twist capture assay
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @oniblock)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_Reference/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oniblock)

**Pull request merged**
