### PR TITLE
update repo to include GRch37 annotation sources + vep 104.3

### PR DESCRIPTION
**Pull request by Addy81**
Resources placeholders added for:
annotation/b37/cadd/v1.6/cadd_whole_genome_SNVs_GRCh37.tsv.gz
annotation/b37/cadd/v1.6/cadd_whole_genome_SNVs_GRCh37.tsv.gz.tbi
annotation/b37/cadd/v1.6/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz
annotation/b37/cadd/v1.6/gnomad.genomes.r2.1.1.indel.tsv.gz.tbi
annotation/b37/clinvar/clinvar_20211113_withChr.vcf.gz
annotation/b37/clinvar/clinvar_20211113_withChr.vcf.gz.tbi
annotation/b37/cosmic/v94/CosmicCodingMuts_v94_grch37.normal.vcf.gz
annotation/b37/cosmic/v94/CosmicCodingMuts_v94_grch37.normal.vcf.gz.tbi
annotation/b37/cosmic/v94/CosmicNonCodingVariants_v94_grch37.normal.vcf.gz
annotation/b37/cosmic/v94/CosmicNonCodingVariants_v94_grch37.normal.vcf.gz.tbi
annotation/b37/gnomad/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz
annotation/b37/gnomad/gnomad.genomes.r2.0.1.sites.noVEP.vcf.gz.tbi
annotation/b37/vep/Homo_sapiens.GRCh37.dna.toplevel.fa.gz
annotation/b37/vep/Homo_sapiens.GRCh37.dna.toplevel.fa.gz.fai
annotation/b37/vep/Homo_sapiens.GRCh37.dna.toplevel.fa.gz.fai.gzi
annotation/b37/vep/homo_sapiens_refseq_vep_104_GRCh37.tar.gz
assets/vep/vep_docker_v104.3/CADD.pm
assets/vep/vep_docker_v104.3/plugin_config.txt
assets/vep/vep_docker_v104.3/vep_v104.3.tar.gz

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/113)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
can check with @mattgarner but I think we're meant to be recording dx file ids in these placeholder files, this will ensure that the version in github points to what is in 001 and we will know if any changes have been made to the files but not the repo

> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/113#-:-MqF_8lV0k0RZANiiawc:b-l1plmp)* status: 1 of 19 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @jethror1)

___
*[annotation/b37/cosmic/v94/CosmicCodingMuts_v94_grch37.normal.vcf.gz, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/113#-MqFZvOW4u9jmSt2Md9F:-MqFZvOX5YsV9NUEMat2:b-ll82vs) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e4cab1558650d0a96b7d9b72d0cdd8737eeacdbe/annotation/b37/cosmic/v94/CosmicCodingMuts_v94_grch37.normal.vcf.gz#L5)):*
> ```
> #Generate authentication string:
> echo "email@example.com:mycosmicpassword" | base64
> ZW1haWxAZXhhbXBsZS5jb206bXljb3NtaWNwYXNzd29yZAo=
> ```

is this your actual auth token?

**Review by mattgarner — COMMENTED** [review]
What @addy81 has done here is consistent with our current practice. This is to document where the file which the placeholder represents was obtained from. 

Inclusion of file-ids is an interesting suggestion - it could be useful to capture this, but of course it would require that you put all of your files into dx before you could update the repo, which is rather backwards to how we usually work.

Let's take that discussion aside as a separate issue - I'm happy with this as it is.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/113#-:-MqKl8dK71sDFTGA_HjM:bis4op4)* status: 1 of 19 files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Comment by jethror1** [comment]
True, but if we do the PR before uploading anything then there's no control/review by anyone except the uploader of whats actually going in, and the person reviewing the PR is just reviewing that it these files 'might' be correct.

It also goes back to this not providing any control / reference to the file content of what is actually in DNAnexus, i.e. if we include file-ids or md5 sums then we can be certain that they are the same file, as they would both change if the file was modified. As it is it is just a reference to a file that should exist.

But then do / would we ever check if these match? If someone modifies a file in 001 and git isn't updated would we know?

I feel like this is a bigger question than just this, and I'd trust this to be right, but I feel like there should be more / better control over whats in the project, but this I'm happy with.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/113#-:-MqKvgtG3iz-cuM7-cTK:bnfp4nl)* status: 1 of 19 files reviewed, 1 unresolved discussion (waiting on @Addy81 and @jethror1)

___
*[annotation/b37/cosmic/v94/CosmicCodingMuts_v94_grch37.normal.vcf.gz, line 5 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/113#-MqFZvOW4u9jmSt2Md9F:-MqFcwPT1VdEN_yW1Kyz:b55h1bw) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e4cab1558650d0a96b7d9b72d0cdd8737eeacdbe/annotation/b37/cosmic/v94/CosmicCodingMuts_v94_grch37.normal.vcf.gz#L5)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Of course not. It is the example given by COSMIC.
</blockquote></details>

was just checking...

**Pull request merged**
