### PR TITLE
FH multiQC config

### PR DESCRIPTION
**Pull request by sophie22**
based on gemini, but modified the following conditional formatting:
vcf_qc: mean het ratio pass between 0.4< and <0.52, warn outside range
remove 'inferred sex' from report
VerifyBAMID contamination is pass <= 5.0% or fail above 5%
kept 'fold 80 base penalty' and 'target bases at 20x' as in gemini

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41)

### CODE REVIEW

**Review by Addy81 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @sophie22)

___
*[dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml, line 20 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-MLSvRC17cYGPUc2H0mz:-MLSvRC17cYGPUc2H0n-:bee9fa9) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e89451aecf07e93f85c83b11dc2357085d2e31f6/dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml#L20)):*
> ```YAML
> 
> # Title to use for the report.
> title: East GLH MultiQC Report for FH
> ```

i am being picky but the title should be a bit different? 
___
*[dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml, line 207 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-MLSvJ3yDy9jIkTNk0jq:-MLSvJ3yDy9jIkTNk0jr:b22ig12) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e89451aecf07e93f85c83b11dc2357085d2e31f6/dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml#L207)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     mean_het_ratio: # vcf_qc mean het ratio column
>         pass:
>             - gt: 0.4
>         warn:
>             - gt: 0.52
>             - lt: 0.4
> ```
</details>


what would happen if it was equal to 0.4 as discussed?
___
*[dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml, line 221 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-MLSuy4O4U9f0ztGFd9o:-MLSuDPN4njiV1iJI699:b-codii1) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e89451aecf07e93f85c83b11dc2357085d2e31f6/dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml#L221)):*
> ```YAML
>     mqc-generalstats-picard-PCT_TARGET_BASES_20X: # Percentage of target bases at 20x    
>         pass:                                     # number in name depends on what is set below
>             -lt: 101
> ```

this is missing a space and it gets coloured differently, I assume that is ok?

Also why is 101 if this is a percentage?

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Addy81)

___
*[dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml, line 20 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-MLSvRC17cYGPUc2H0mz:-MLSwCJa4qTUe7Gu4SxT:b-m8crai) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e89451aecf07e93f85c83b11dc2357085d2e31f6/dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml#L20)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

i am being picky but the title should be a bit different? 
</blockquote></details>

sure, what do you want the title to be?
___
*[dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml, line 207 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-MLSvJ3yDy9jIkTNk0jq:-MLSwH_51TBgxbu3Zvl2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e89451aecf07e93f85c83b11dc2357085d2e31f6/dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml#L207)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

> ```
>     mean_het_ratio: # vcf_qc mean het ratio column
>         pass:
>             - gt: 0.4
>         warn:
>             - gt: 0.52
>             - lt: 0.4
> ```

what would happen if it was equal to 0.4 as discussed?
</blockquote></details>

Done.
___
*[dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml, line 221 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-MLSuy4O4U9f0ztGFd9o:-MLSwWcj7iWRO5BU_JDA:b-8ikwd5) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/e89451aecf07e93f85c83b11dc2357085d2e31f6/dynamic_files/multiqc_config/FH_multiqc_config_v1.0.0.yaml#L221)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

this is missing a space and it gets coloured differently, I assume that is ok?

Also why is 101 if this is a percentage?

</blockquote></details>

added the space. lt 101 so that I don't have to have lt 100 AND eq 100. plain laziness

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Addy81 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/41#-:-MLSzrbfCX40tSjnaaqY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
