### PR TITLE
update exon file

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/15)

### CODE REVIEW

**Comment by mattgarner** [comment]
Regions in this file need to match the regions in the coverage files. Those will now be +/- 5bp, so this needs to be adjusted to match.

**Comment by Yu-jinKim** [comment]
Is the gff_to_bed repo used for things other than the exon file? I'll need to add things (options for creating the exon file in the argparse) if it is

**Comment by mattgarner** [comment]
Yes, it's used to create bed files too. If the same code could make both files that would be great.

**Comment by mattgarner** [comment]
Reassigning PR to @woook as I have now contributed content and cannot review / merge

**Pull request merged**
