### PR TITLE
1.0.7 somalier

### PR DESCRIPTION
**Pull request by Aisha-D**
Added somalier custom table to MultiQC config file
Uploaded download info for somalier docker image and sites GRCh37 vcf file

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65)

### CODE REVIEW

**Review by sophie22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml, line 184 at r2](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65#-MWUFOH22w_DXHc1znoo:-MWUFOH22w_DXHc1znop:b-nndler) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/0ea1d8d8c4c65cb4efba311b7dadc2b96571168a/dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml#L184)):*
> ```YAML
>     - warn: '#f0ad4e'
>     - fail: '#d9534f'
>     - true: '#5cb85c'
> ```

the colour for 'true' is the same as 'pass', and 'false' as 'fail', so I recommend that instead of redefining the same colours, you could use the 'pass/fail' in the conditionals below
___
*[dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml, line 263 at r2](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65#-MWUFyg24RLS1rOiEjnu:-MWUFyg24RLS1rOiEjnv:b6w7cb7) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/0ea1d8d8c4c65cb4efba311b7dadc2b96571168a/dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml#L263)):*
> ```YAML
>     somalier_files:  # Somalier Matching Sex column
>         true:
>             - s_eq: 'true'
> ```

replace with 'pass' and 'fail'

**Review by sophie22 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml, line 407 at r2](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65#-MWUGFNj3YrecBEqNnEO:-MWUGFNj3YrecBEqNnEP:bne31tp) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/0ea1d8d8c4c65cb4efba311b7dadc2b96571168a/dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml#L407)):*
> ```YAML
> 
> exclude_modules:
>   - somalier
> ```

this might need to be 4 space-wide indentation to match the others

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml, line 184 at r2](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65#-MWUFOH22w_DXHc1znoo:-MWV3xi39kH8xkd_LUzY:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/0ea1d8d8c4c65cb4efba311b7dadc2b96571168a/dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml#L184)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

the colour for 'true' is the same as 'pass', and 'false' as 'fail', so I recommend that instead of redefining the same colours, you could use the 'pass/fail' in the conditionals below
</blockquote></details>

Done.
___
*[dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml, line 263 at r2](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65#-MWUFyg24RLS1rOiEjnu:-MWV3yA26XeA367GP_qt:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/0ea1d8d8c4c65cb4efba311b7dadc2b96571168a/dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml#L263)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

replace with 'pass' and 'fail'
</blockquote></details>

Done.
___
*[dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml, line 407 at r2](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65#-MWUGFNj3YrecBEqNnEO:-MWV4-KmDUllCdSNoox9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/0ea1d8d8c4c65cb4efba311b7dadc2b96571168a/dynamic_files/multiqc_config/gemini_multiqc_config_v1.0.7.yaml#L407)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

this might need to be 4 space-wide indentation to match the others
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Review by sophie22 — APPROVED** [review]

**Pull request merged**
