### PR TITLE
added KRT8 and CPA1 to g2t

### PR DESCRIPTION
**Pull request by jethror1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dynamic_files/nirvana_genes2transcripts/nirvana_genes2transcripts_2010_200910, line 634 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42#-MI55_g6EF_9qLtNL_Uh:-MI55_g6EF_9qLtNL_Ui:b-rslh6) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/921ef42034eaebe8a72641fe9a6360fbb35cc50d/dynamic_files/nirvana_genes2transcripts/nirvana_genes2transcripts_2010_200910#L634)):*
> ```
> CPA1    NM_001868.3
> ```
Tabs not spaces please
___
*[dynamic_files/nirvana_genes2transcripts/nirvana_genes2transcripts_2010_200910, line 1583 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42#-MI55cWZAsDY1w6X4_Ft:-MI55cWZAsDY1w6X4_Fu:b-z0tmin) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/921ef42034eaebe8a72641fe9a6360fbb35cc50d/dynamic_files/nirvana_genes2transcripts/nirvana_genes2transcripts_2010_200910#L1583)):*
> ```
> KRT8    NM_002273.3
> ```
Tabs not spaces please

**Review by woook — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by woook — APPROVED** [review]
Thought I'd finish off the code review as I was here anyway.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42#-:-MI9-oo222jF74tWwasM:b-faktol)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by woook — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42#-:-MI9-vOX13SwNNtXDDkX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by woook — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by woook — APPROVED** [review]
> Dismissed @mattgarner from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
