### PR TITLE
Myeloid config v1.0.0.

### PR DESCRIPTION
**Pull request by sophie22**
Add multiQC config file for Myeloid:
remove sentieon, move bcl2fastq to the end of report, modify columns in Gen Stats, include custom % coverage, remove Target Region coverage plot from Picard and Per Base Sequence Content plot from FastQC sections. For conditional formatting: remove all 'fail' as only warnings needed, removed conditions that are no longer needed

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56)

### CODE REVIEW

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56)* status: all files reviewed, 2 unresolved discussions (waiting on @sophie22)

___
*[dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml, line 174 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56#-MSDHQBeDQ8YcEmKC-wX:-MSDHQBeDQ8YcEmKC-wY:bb6h636) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/32c466f45e0459a5e457f7c195afe2fac4d43018/dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml#L174)):*
> ```YAML
>     mqc-generalstats-picard-PCT_TARGET_BASES_100X:
>         pass:
>             - lt: 101
> ```

101?
___
*[dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml, line 183 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56#-MSDHSKF2d_EQUhbf-Qm:-MSDHSKF2d_EQUhbf-Qn:bb6h636) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/32c466f45e0459a5e457f7c195afe2fac4d43018/dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml#L183)):*
> ```YAML
>     mqc-generalstats-custom_coverage-250x:
>         pass:
>             - lt: 101
> ```

101?

**Review by sophie22 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56)* status: all files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml, line 174 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56#-MSDHQBeDQ8YcEmKC-wX:-MSDI0y16U4FUxFIM5r7:bylp4f3) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/32c466f45e0459a5e457f7c195afe2fac4d43018/dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml#L174)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

101?
</blockquote></details>

less than 101 so that no need for separate lines as less than and equal to 100
___
*[dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml, line 183 at r1](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56#-MSDHSKF2d_EQUhbf-Qm:-MSDI3R0CBoVoDUp_GPm:b-h7ps8l) ([raw file](https://github.com/eastgenomics/eggd_001_reference/blob/32c466f45e0459a5e457f7c195afe2fac4d43018/dynamic_files/multiqc_config/myeloid_multiqc_config_v1.0.0.yaml#L183)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

101?
</blockquote></details>

less than 101 so that no need for separate lines as less than and equal to 100

**Review by Yu-jinKim — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_001_reference/56)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by mattgarner** [comment]
Did this review include a check that the threshold values set in the config match those which were required? I don't see a list/link to the required thresholds for the reviewer to compare to the config file

**Pull request merged**
